B0: 1.5
B1: 100
TR: 2700
components:
- {CS: 0.0, Meq: 1.0, T1: 2400, T2: 160, name: CSF}
- {CS: 0.0, Meq: 1.0, T1: 790, T2: 92, name: WM}
- {CS: 0.0, Meq: 1.0, T1: 920, T2: 101, name: GM}
isochromatStep: 0.01
nIsochromats: 1
nTR: 1
outFile3D: FLAIR_3D.gif
outFileMxy: ''
outFileMz: FLAIR_long.gif
pulseSeq:
- {FA: 180, t: 0}
- {FA: 90, t: 1680}
- {FA: 180, t: 1710}
speed: 0.1
title: FLAIR
