B0: 1.5
B1: 1.0
TR: 40
components:
- {CS: 0.0, Meq: 1.0, T1: 790.0, T2: 92.0, name: ''}
isochromatStep: 0.01
nIsochromats: 20
nTR: 1
outFile3D: SE_3D.gif
outFileMxy: 'SE_xy.gif'
outFileMz: 'SE_z.gif'
pulseSeq:
- {FA: 90, t: 0}
- {FA: 180, t: 10}
speed: 0.01
title: Spin Echo
